language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6-dev"

script:
  - python setup.py test

deploy:
  provider: pypi
  user: joernhees
  password:
    secure: $ENC_PYPI_PW
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: pythoncircus/splendid
